import React from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { Database } from '@/types/database';

type CalendarEvent = Database['public']['Tables']['calendar_events']['Row'];

const EVENT_TYPE_LABELS: Record<string, string> = {
  holiday: 'Holiday',
  exam: 'Exam',
  event: 'Event',
  closure: 'Closure',
  meeting: 'Meeting',
};

interface CalendarPDFProps {
  schoolName: string;
  month: string; // yyyy-MM format
  events: CalendarEvent[];
}

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
  },
  header: {
    marginBottom: 20,
    borderBottom: 2,
    borderColor: '#000000',
    paddingBottom: 10,
  },
  schoolName: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  title: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 3,
  },
  subtitle: {
    fontSize: 10,
    textAlign: 'center',
    color: '#666666',
  },
  table: {
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000000',
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: 'row',
  },
  tableHeader: {
    backgroundColor: '#f3f4f6',
  },
  tableCell: {
    flex: 1,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000000',
    padding: 6,
    fontSize: 9,
  },
  tableCellHeader: {
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tableCellDate: {
    width: 40,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tableCellDay: {
    width: 50,
    textAlign: 'center',
    color: '#666666',
  },
  tableCellEvent: {
    flex: 1,
  },
  eventType: {
    fontWeight: 'bold',
  },
  emptyRow: {
    color: '#999999',
    fontStyle: 'italic',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 9,
    color: '#666666',
    borderTop: 1,
    borderColor: '#e5e7eb',
    paddingTop: 8,
  },
});

const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

const CalendarPDFDocument: React.FC<CalendarPDFProps> = ({
  schoolName,
  month,
  events,
}) => {
  const [year, monthNum] = month.split('-').map(Number);
  const monthName = new Date(year, monthNum - 1).toLocaleString('en-US', { month: 'long' });

  // Build days in month
  const daysInMonth = new Date(year, monthNum, 0).getDate();
  const days: { date: number; day: string; events: CalendarEvent[] }[] = [];
  for (let d = 1; d <= daysInMonth; d++) {
    const dateObj = new Date(year, monthNum - 1, d);
    const dateStr = `${year}-${String(monthNum).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
    const dayEvents = events.filter((e) => e.event_date === dateStr);
    days.push({
      date: d,
      day: DAYS[dateObj.getDay()],
      events: dayEvents,
    });
  }

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.schoolName}>{schoolName}</Text>
          <Text style={styles.title}>Academic Calendar - {monthName} {year}</Text>
          <Text style={styles.subtitle}>{events.length} event{events.length !== 1 ? 's' : ''} this month</Text>
        </View>

        <View style={styles.table}>
          {/* Header */}
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={[styles.tableCell, styles.tableCellDate, styles.tableCellHeader]}>Date</Text>
            <Text style={[styles.tableCell, styles.tableCellDay, styles.tableCellHeader]}>Day</Text>
            <Text style={[styles.tableCell, styles.tableCellEvent, styles.tableCellHeader]}>Events</Text>
          </View>

          {/* Days */}
          {days.map(({ date, day, events: dayEvents }) => (
            <View key={date} style={styles.tableRow}>
              <Text style={[styles.tableCell, styles.tableCellDate]}>{date}</Text>
              <Text style={[styles.tableCell, styles.tableCellDay]}>{day}</Text>
              <View style={[styles.tableCell, styles.tableCellEvent]}>
                {dayEvents.length === 0 ? (
                  <Text style={styles.emptyRow}>-</Text>
                ) : (
                  dayEvents.map((evt) => (
                    <Text key={evt.id}>
                      <Text style={styles.eventType}>
                        [{EVENT_TYPE_LABELS[evt.event_type] || evt.event_type}]
                      </Text>
                      {' '}{evt.title}
                      {evt.description ? ` - ${evt.description}` : ''}
                    </Text>
                  ))
                )}
              </View>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by SKULI on {new Date().toLocaleDateString('en-GB')}
        </Text>
      </Page>
    </Document>
  );
};

export async function generateCalendarPDF(
  schoolName: string,
  month: string,
  events: CalendarEvent[]
): Promise<Blob> {
  const doc = <CalendarPDFDocument schoolName={schoolName} month={month} events={events} />;
  return pdf(doc).toBlob();
}

export default CalendarPDFDocument;
