#!/usr/bin/env node
/**
 * build-schema.mjs
 *
 * Regenerates supabase/schema.sql by concatenating all SQL files in
 * supabase/migrations/ in numeric order. The Supabase CLI convention
 * picks up only top-level *.sql files in migrations/, so anything
 * inside _legacy/ or other subfolders is skipped.
 *
 * Run this after:
 *   - Adding a new migration
 *   - Editing an existing base migration (00001-00032)
 *   - Moving files in/out of _legacy/
 *
 * Usage: node scripts/build-schema.mjs
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const migrationsDir = join(repoRoot, "supabase", "migrations");
const outputPath = join(repoRoot, "supabase", "schema.sql");

/**
 * Recursively walk migrations/ but skip any directory that starts with
 * underscore (`_legacy/`, `_scratch/`, etc.). The Supabase CLI ignores
 * subdirectories anyway, so this matches its behaviour.
 */
function walkMigrations(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith("_")) continue; // skip _legacy, _scratch, etc.
      files.push(...walkMigrations(full));
    } else if (entry.isFile() && entry.name.endsWith(".sql")) {
      files.push(full);
    }
  }
  return files;
}

const allFiles = walkMigrations(migrationsDir).sort();
if (allFiles.length === 0) {
  console.error(`No .sql files found in ${migrationsDir}`);
  process.exit(1);
}

const header = `-- =============================================================================
-- SKULI SaaS: Consolidated Schema
-- =============================================================================
-- This file is the canonical end-state of the database, generated by
-- concatenating all supabase/migrations/*.sql (top-level only) in
-- numeric order. Files in subdirectories (e.g. _legacy/) are
-- excluded — they are history-only and not part of the canonical
-- migration stream.
--
-- Use this for:
--   1. Fresh database setup (new Supabase project, local dev).
--   2. Disaster recovery when the migration history is lost.
--
-- DO NOT apply this to a live database that has already been migrated.
-- Use \`supabase db push\` for live updates — that runs the base
-- migrations in order and respects supabase_migrations.schema_migrations.
--
-- Regenerate:  node scripts/build-schema.mjs
-- Generated:   ${new Date().toISOString()}
-- Source files: ${allFiles.length}
-- =============================================================================

`;

const parts = [header];
for (const file of allFiles) {
  const rel = file
    .replace(repoRoot + "\\", "")
    .replace(/\\/g, "/");
  parts.push(`\n-- ----------------------------------------------------------------------------\n`);
  parts.push(`-- Source: ${rel}\n`);
  parts.push(`-- ----------------------------------------------------------------------------\n\n`);
  parts.push(readFileSync(file, "utf8"));
}

const out = parts.join("");
writeFileSync(outputPath, out, "utf8");
const sizeKb = (statSync(outputPath).size / 1024).toFixed(1);
console.log(`✓ Wrote ${sizeKb} KB to ${outputPath.replace(repoRoot + "\\", "")} (${allFiles.length} files)`);
