"use client";

import * as React from "react";
import * as ToastPrimitives from "@radix-ui/react-toast";
import { cva, type VariantProps } from "class-variance-authority";
import { CheckCircle2, AlertTriangle, AlertCircle, Info, X } from "lucide-react";
import { cn } from "@/lib/utils/cn";

const ToastProvider = ToastPrimitives.Provider;

const ToastViewport = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Viewport>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Viewport>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Viewport
    ref={ref}
    className={cn(
      // Always top-right, full width on mobile, fixed 380px on >= sm.
      "fixed top-4 right-4 z-[100] flex max-h-screen w-[calc(100vw-2rem)] sm:max-w-[380px] flex-col gap-3 outline-none",
      className
    )}
    {...props}
  />
));
ToastViewport.displayName = ToastPrimitives.Viewport.displayName;

const toastVariants = cva(
  // `group` is the hover-pause trigger. `data-[state=open]:animate-in` etc.
  // give us slide+fade on enter and exit. The bottom border doubles as a
  // progress bar — we shrink its width with a CSS animation that runs for
  // `duration` ms (set inline by Toaster), paused while the toast is
  // hovered/focused via `group-hover:animation-play-state:paused`.
  //
  // COLOR NOTE: the project's palette only defines the *-50/100/400/500/600/700
  // stops for each semantic scale (see app/globals.css). Classes like
  // `border-danger-200` or `text-danger-800` are NOT generated by Tailwind,
  // which leaves the toast borderless and the text inheriting from <body>.
  // Stick to the stops that actually exist in the theme.
  "group pointer-events-auto relative flex w-full items-start gap-3 overflow-hidden rounded-xl border p-4 pr-10 shadow-pop backdrop-blur-sm transition-all data-[swipe=cancel]:translate-x-0 data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)] data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-80 data-[state=closed]:slide-out-to-right-full data-[state=open]:slide-in-from-right-full",
  {
    variants: {
      variant: {
        default:
          "border-border-strong bg-card text-text-heading",
        success:
          "border-success-500 bg-success-50 text-success-700 dark:bg-success-900/40 dark:text-success-400",
        destructive:
          "border-danger-500 bg-danger-50 text-danger-700 dark:bg-danger-900/40 dark:text-danger-400",
        warning:
          "border-warning-500 bg-warning-50 text-warning-700 dark:bg-warning-900/40 dark:text-warning-400",
        info:
          "border-info-500 bg-info-50 text-info-700 dark:bg-info-900/40 dark:text-info-400",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

const Toast = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Root> &
    VariantProps<typeof toastVariants>
>(({ className, variant, ...props }, ref) => {
  return (
    <ToastPrimitives.Root
      ref={ref}
      className={cn(toastVariants({ variant }), className)}
      {...props}
    />
  );
});
Toast.displayName = ToastPrimitives.Root.displayName;

/**
 * Thin progress bar pinned to the bottom of the toast. Width animates from
 * 100% to 0% over `duration` ms, then `forwards` holds at 0% until the toast
 * unmounts. The animation pauses while the user is hovering/focusing the
 * toast (group:hover / group:focus-within).
 */
const ToastProgress = React.forwardRef<
  HTMLDivElement,
  { variant?: ToastProps["variant"]; duration?: number }
>(({ variant, duration = 5000 }, ref) => {
  const colorCls =
    variant === "success"
      ? "bg-success-500"
      : variant === "destructive"
      ? "bg-danger-500"
      : variant === "warning"
      ? "bg-warning-500"
      : variant === "info"
      ? "bg-info-500"
      : "bg-border-strong";
  return (
    <div
      ref={ref}
      aria-hidden="true"
      className="absolute bottom-0 left-0 right-0 h-1 bg-border/30 overflow-hidden"
    >
      <div
        className={cn(
          "h-full origin-left",
          colorCls,
          // Animation: shrink width from 100% to 0% over `duration` ms.
          // The animation is paused while the user hovers/focuses the toast
          // (group:hover / group:focus-within) so they can finish reading.
          "animate-toast-progress group-hover:[animation-play-state:paused] group-focus-within:[animation-play-state:paused]"
        )}
        style={{ animationDuration: `${duration}ms` }}
      />
    </div>
  );
});
ToastProgress.displayName = "ToastProgress";

const ToastIcon = ({ variant }: { variant: ToastProps["variant"] }) => {
  // Same caveat as the variants block: only the *-50/100/400/500/600/700 stops
  // are defined in the theme, so use the 500 in light mode (saturated on the
  // tinted -50 background) and the 400 in dark mode (light on the dark
  // -900/40 background). Both give a strong contrast bump over the body text.
  const cls = "h-5 w-5 shrink-0 mt-0.5";
  switch (variant) {
    case "success":     return <CheckCircle2  className={cn(cls, "text-success-500 dark:text-success-400")} />;
    case "destructive": return <AlertCircle    className={cn(cls, "text-danger-500  dark:text-danger-400")} />;
    case "warning":     return <AlertTriangle  className={cn(cls, "text-warning-500 dark:text-warning-400")} />;
    case "info":        return <Info           className={cn(cls, "text-info-500    dark:text-info-400")} />;
    default:            return null;
  }
};

const ToastAction = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Action>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Action>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Action
    ref={ref}
    className={cn(
      "inline-flex h-8 shrink-0 items-center justify-center rounded-md border border-border bg-card px-3 text-sm font-medium transition-colors",
      "hover:bg-card-hover focus:outline-none focus:ring-2 focus:ring-border focus:ring-offset-2",
      "disabled:pointer-events-none disabled:opacity-50",
      className
    )}
    {...props}
  />
));
ToastAction.displayName = ToastPrimitives.Action.displayName;

const ToastClose = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Close>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Close>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Close
    ref={ref}
    aria-label="Close notification"
    className={cn(
      // Always visible (not just on hover) so it's discoverable on touch and
      // keyboard nav. Top-right, sits inside the padded area.
      "absolute right-2 top-2 inline-flex h-7 w-7 items-center justify-center rounded-md text-current opacity-70 transition-opacity",
      "hover:opacity-100 hover:bg-black/5 dark:hover:bg-white/10 focus:opacity-100 focus:outline-none focus:ring-2 focus:ring-current/30",
      className
    )}
    toast-close=""
    {...props}
  >
    <X className="h-4 w-4" />
  </ToastPrimitives.Close>
));
ToastClose.displayName = ToastPrimitives.Close.displayName;

const ToastTitle = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Title>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Title>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Title
    ref={ref}
    className={cn("text-sm font-semibold leading-snug", className)}
    {...props}
  />
));
ToastTitle.displayName = ToastPrimitives.Title.displayName;

const ToastDescription = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Description>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Description>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Description
    ref={ref}
    // No opacity on the description — it inherits color from the variant and
    // an additional 90% opacity on top produced hard-to-read text in dark mode.
    className={cn("text-sm leading-snug mt-0.5", className)}
    {...props}
  />
));
ToastDescription.displayName = ToastPrimitives.Description.displayName;

type ToastProps = React.ComponentPropsWithoutRef<typeof Toast>;
type ToastActionElement = React.ReactElement<typeof ToastAction>;

export {
  type ToastProps,
  type ToastActionElement,
  ToastProvider,
  ToastViewport,
  Toast,
  ToastTitle,
  ToastDescription,
  ToastClose,
  ToastAction,
  ToastIcon,
  ToastProgress,
};
