"""Patch remaining routes to use handleRouteError instead of leaking err.message.

Audit §3.1 / §8.10: many routes still end with
    const status = getErrorStatus(err);
    const message = err instanceof Error ? err.message : "Internal server error";
    return errorResponse(message, status);
which leaks raw exception text to clients. We replace those tails with
handleRouteError(err, route). We also drop the now-unused imports
getErrorStatus and (where no longer used) errorResponse, while keeping
errorResponse where it's still called for client-validated 400s.

The script intentionally uses the simplest possible substitutions and
is conservative: it only patches the exact tail pattern. If a route
intentionally echoes err.message because the error was generated by a
zod check on the request body (which the user can fix), it is left
alone — those messages are intentional user-facing 400s.
"""
import re
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Asiimwe Mark Amooti\Desktop\skulii-os\app\api")
ROUTE_RE = re.compile(r"route\.ts$")

# Per-route name for logging context (filename -> route label).
ROUTE_LABELS: dict[str, str] = {}


def route_label(path: Path) -> str:
    rel = path.relative_to(ROOT)
    parts = rel.parts
    if len(parts) == 1:
        return f"GET /api/{parts[0]}"
    # build a method-style label from the request handlers in the file
    return "/".join(parts).replace("\\", "/")


# Pattern matches the exact two-line + errorResponse tail that the audit flagged.
# Allow flexible spacing.
TAIL_RE = re.compile(
    r"    const status = getErrorStatus\(err\);[ \t]*\n"
    r"    const message = err instanceof Error \? err\.message : .Internal server error.;[ \t]*\n"
    r"    return errorResponse\(message, status\);[ \t]*\n"
    r"  \}",
)

# Some routes use a slightly different variable name (e).
TAIL_RE_ALT = re.compile(
    r"    return errorResponse\(e instanceof Error \? e\.message : .Error., getErrorStatus\(e\)\);[ \t]*\n"
    r"  \}",
)


def patch_route(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    label = route_label(path)
    ROUTE_LABELS[label] = label

    new_text, count = TAIL_RE.subn(
        "    return handleRouteError(err, \"" + label + "\");\n  }",
        text,
    )
    if count == 0:
        new_text, count = TAIL_RE_ALT.subn(
            "    return handleRouteError(e, \"" + label + "\");\n  }",
            text,
        )
    if count == 0:
        return False

    # Clean up imports: drop getErrorStatus if no longer referenced.
    if "getErrorStatus(" not in new_text:
        # remove "getErrorStatus" tokens from the named-import list.
        new_text = re.sub(
            r"(\n\s*)getErrorStatus(,?)",
            "",
            new_text,
        )
        new_text = re.sub(
            r"(\n\s*),(\s*\n)",
            "\n",
            new_text,
        )
    if "errorResponse(" not in new_text and "errorResponse " not in new_text:
        new_text = re.sub(
            r"(\n\s*)errorResponse(,?)",
            "",
            new_text,
        )

    path.write_text(new_text, encoding="utf-8")
    return True


def main() -> int:
    patched = []
    for route in ROOT.rglob("route.ts"):
        if patch_route(route):
            patched.append(str(route.relative_to(ROOT)))
    print(f"Patched {len(patched)} routes:")
    for p in patched:
        print(f"  - {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())