-- =============================================================================
-- SKULI SaaS: Dashboard MV privilege lock-down (Audit §12.2)
-- Migration 0031
--
-- NOTE: The mv_dashboard_* materialised views are created in 0042, which runs
-- after this file. The REVOKE statements that originally lived here have been
-- moved into 0042 so they execute immediately after the views are created.
-- This file is intentionally a no-op to preserve migration numbering.
-- =============================================================================
